# Generated by Django 4.2.1 on 2023-05-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_bazar", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="imagen_url",
            field=models.URLField(),
        ),
    ]
