# Generated by Django 4.2.1 on 2023-05-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_bazar", "0002_alter_producto_imagen_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="imagen_url",
            field=models.URLField(max_length=600),
        ),
    ]
