# Generated by Django 4.2.1 on 2023-05-17 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_bazar", "0003_alter_producto_imagen_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="precio",
            field=models.PositiveIntegerField(default=50, verbose_name=50),
            preserve_default=False,
        ),
    ]
